## Numpy

In [2]:
import numpy as np

In [5]:
x=np.array([10,20,30,40,50,'hola'])
x

array(['10', '20', '30', '40', '50', 'hola'], dtype='<U11')

In [4]:
lista=[10,20,30,40,50]
lista

[10, 20, 30, 40, 50]

In [6]:
x=np.array([10,20,30,40,50])
x

array([10, 20, 30, 40, 50])

In [7]:
x[4]

50

In [8]:
x[2:4]

array([30, 40])

In [9]:
x[2:5]

array([30, 40, 50])

In [11]:
z=np.arange(1,20,1)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
z=np.arange(start=1, stop=21, step=0.5)
z

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [14]:
y=np.linspace(1,20,20)
y

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [16]:
y=np.linspace(1,20,2000)
## puede ser util para hacer graficas o evaluación de funciones
y

array([ 1.        ,  1.00950475,  1.0190095 , ..., 19.9809905 ,
       19.99049525, 20.        ])

In [19]:
x=np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
x=np.ones((10,15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
y = np.array([[10,20,30,40,50],[60,70,80,90,100]])
y

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [23]:
np.zeros_like(y)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.ones_like(y)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
y = np.array([[10,20,30,40,50],[60,70,80,90,100]])
rango=y.ndim
#rango del tensor es 2 la cantidad de valores que requiero para gestionar la información dentro del tensor
dimensiones=y.shape
print(f"El rango del tensor es:{rango} y las dimensiones son:{dimensiones}")
#cada variable es una dimensión
#f en la funcion print le damos el permiso de escribir de forma str y referencia a variables

El rango del tensor es:2 y las dimensiones son:(2, 5)


### operaciones

In [27]:
v=np.array([1,2,3,4])
w=np.array([5,6,7,8])

In [30]:
print("suma: ", v + w)
print("resta: ", v - w)
print("multiplicacion: ", v * w)
print("division: ", v / w)
print("modulo: ", v % w)
print("--- Broadcasting ---")
print("mult escalar: ", 2*w)
print("suma escalar: ", 5 + v)
print("resta escalar: ", 4 - w)
print("division escalar: ", w / 8)
print("modulo escalar: ", w % 2)

#modulo es el residuo de la división

suma:  [ 6  8 10 12]
resta:  [-4 -4 -4 -4]
multiplicacion:  [ 5 12 21 32]
division:  [0.2        0.33333333 0.42857143 0.5       ]
modulo:  [1 2 3 4]
---Broadcasting----
mult escalar:  [10 12 14 16]
suma escalar:  [6 7 8 9]
resta escalar:  [-1 -2 -3 -4]
division escalar:  [0.625 0.75  0.875 1.   ]
modulo escalar:  [1 0 1 0]


In [31]:
x = np.array([1,2, 3,4, 5, 6, 7, 3, 3, 4, 5])
x_nan = np.array([1, 2, 3, 4, 5, 6, 7, np.nan, 5, 9, np.nan])

print(x)
print(x_nan)

[1 2 3 4 5 6 7 3 3 4 5]
[ 1.  2.  3.  4.  5.  6.  7. nan  5.  9. nan]


In [32]:
np.mean(x_nan)

nan

In [33]:
np.nanmean(x_nan)

4.666666666666667

In [34]:
print(np.mean(x))
print(np.nanmean(x_nan))
print(np.median(x))
print(np.nanmedian(x_nan))
print(np.std(x))
print(np.nanstd(x_nan))
print(np.max(x))
print(np.nanmax(x_nan))
print(np.min(x))
print(np.nanmin(x_nan))
print(np.var(x))
print(np.nanvar(x_nan))
print(np.sum(x))
print(np.nansum(x_nan))
print(np.prod(x))
print(np.nanprod(x))

3.909090909090909
4.666666666666667
4.0
5.0
1.6762808104168887
2.357022603955158
7
9.0
1
1.0
2.809917355371901
5.5555555555555545
43
42.0
907200
907200


## Reshape

In [38]:
x=np.arange(1,11,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.reshape(x,(2,5))
## cambiarle la forma a un arreglo

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
np.reshape(x,(5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [41]:
np.reshape(x,(3,5))
#error porque la data no da para hacer el arreglo

SyntaxError: unexpected EOF while parsing (26567007.py, line 1)

In [42]:
x # Vector fila

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.reshape(x,(10,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [44]:
np.reshape(x,(-1,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

### Performance

In [54]:
from time import time

In [59]:
x=np.linspace(1,10000000,20000000)
b0=5
b1=2
y=np.empty_like(x)
inicio = time()
for index, value in enumerate(x):
    y[index]=b0+b1*value
fin=time()

print(f"El tiempo de ejecucion es {fin-inicio}")    

El tiempo de ejecucion es 26.922301292419434
